version: 2.1


build_on_master: &build_on_master
  filters:
    tags:
      only: /^v.*/
    branches:
      only: master


workflows:
  version: 2
  circleci-github:
    jobs:
      - test_go:
          <<: *build_on_master

jobs:
  test_go:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.16.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run test
          command: make test