version: 2.1


build_on_master: &build_on_master
  filters:
    tags:
      only: /^v.*/
    branches:
      only: master

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

workflows:
  version: 2
  circleci-github:
    jobs:
      - unit_testing_go:
          <<: *build_on_master
      - aws-ecr/build-and-push-image:
          <<: *build_on_master
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id:  AWS_ACCESS_KEY_ID
          aws-secret-access-key:  AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          dockerfile: Dockerfile
          path: ./
          repo: eeeffllsiss
          tag: latest

          requires:
            - unit_testing_go

jobs:
  unit_testing_go:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.16.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run test
          command: make test
  aws-ecr/build-and-push-image:
    working_directory: ~/repo
    executor:
      name: docker/docker
      tag: '3.6'
    steps:

      - checkout
      #- docker/install-docker-compose
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: ECR - Docker Login
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f0z2q6f8
            echo "${PASS_PRIVATE_REGISTRY}" | docker login ${URL_PRIVATE_REGISTRY}  --username ${USER_PRIVATE_REGISTRY} --password-stdin 
      - run:
          name: Build Docker image TAG
          command: |
            TAG="0.1.<< pipeline.number >>"
            docker build -t $AWS_ECR_ACCOUNT_URL/eeeffllsiss:$TAG .
      - run:
          name: Push Docker image
          command: |
            TAG="0.1.<< pipeline.number >>"
            docker push $AWS_ECR_ACCOUNT_URL/eeeffllsiss:$TAG